### ISSUE TITLE
Cannot deploy to cloudflare

### ISSUE THREAD

**Issue by apokaliptis** [CaptainCodeman/svelte-kit-bot-block#2]
I was trying to deploy my project to cloudflare, but I got this error:

```
Using @sveltejs/adapter-cloudflare
✘ [ERROR] Could not resolve "net"

    .svelte-kit/output/server/chunks/hooks.server.js:1:21:
      1 │ import { isIP } from "net";
        ╵                      ~~~~~

  Cannot use "net" when deploying to Cloudflare.
```

Which appears to be originating from the `src/lib/index.ts` file in this project.

At the moment I haven't been using any IP blocking features, only blocking by pathnames.

**Versions:**

```
node v20.17.0
pnpm 9.9.0
svelte 5.0.0-next.243
@sveltejs/kit ^2.5.26
@sveltejs/adapter-cloudflare ^4.7.2
svelte-kit-bot-block ^0.0.7
```

**Comment by CaptainCodeman** [comment]
Cloudflare's runtime isn't node, so doesn't support all the built-in node modules. You may be able to [configure it to add polyfills](https://developers.cloudflare.com/workers/runtime-apis/nodejs/) to see if that works.
